import Link from "next/link";
const services=[["01","Brand Strategy","Positioning, identity, campaigns and a clear reason to choose you."],["02","Social & Content","Content systems, reels, social management and always-on storytelling."],["03","Performance","Meta, Google, lead funnels, CRO and performance intelligence."],["04","AI & Automation","AI agents, WhatsApp workflows, CRM automation and internal systems."],["05","Web & Digital","Premium websites, landing pages, product experiences and conversion systems."],["06","Production","Ad films, photography, motion, creators and campaign-ready visual production."]];
const industries=["Real Estate","Luxury & Lifestyle","Healthcare","Education","Hospitality","Technology","Retail & E-commerce","Entertainment"];
const events=["Marriages & Weddings","Red Carpet & Entertainment","Corporate Events","Launches & Experiences"];
export default function Home(){return <main className="site">
<nav className="nav2"><Link href="/" className="wordmark">DIGITALE<span>®</span></Link><div className="navlinks"><a href="#services">Capabilities</a><a href="#work">Work</a><a href="#industries">Industries</a><a href="#events">Experiences</a><a href="#contact" className="navcta">Start a project ↗</a></div></nav>
<section className="hero2"><div className="heroKicker">DIGITALE MEDIA · AI × CREATIVE × GROWTH</div><h1>We make brands<br/><i>matter.</i></h1><p>Strategy, creative, technology and performance—built as one connected growth system for ambitious brands.</p><div className="heroBtns"><a href="#contact" className="limeBtn">Build with us ↗</a><a href="#services" className="ghostBtn">Explore capabilities ↓</a></div><div className="heroMeta"><span>INDIA / HYDERABAD</span><span>AI-FIRST DIGITAL AGENCY</span><span>CREATIVE · TECH · GROWTH</span></div></section>
<section className="proof"><div><strong>01</strong><span>STRATEGY</span></div><div><strong>02</strong><span>CREATIVE</span></div><div><strong>03</strong><span>TECHNOLOGY</span></div><div><strong>04</strong><span>GROWTH</span></div></section>
<section id="services" className="section2"><div className="sectionHead"><div className="eyebrow2">CAPABILITIES</div><h2>Everything your<br/><em>growth needs.</em></h2><p>Not a collection of disconnected services. A single team connecting brand, media, technology and measurable growth.</p></div><div className="serviceGrid">{services.map(s=><article key={s[0]}><span className="num">{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><a href="#contact">Explore ↗</a></article>)}</div></section>
<section id="work" className="work2"><div className="eyebrow2">SELECTED WORK / CAMPAIGNS</div><h2>Ideas are cheap.<br/><span>Execution isn't.</span></h2><div className="workGrid"><article className="workCard wide"><div className="fakeVisual v1"><span>REAL ESTATE<br/>GROWTH SYSTEM</span></div><div><small>01 · PROPTECH / PERFORMANCE</small><h3>Turn attention into qualified demand.</h3></div></article><article className="workCard"><div className="fakeVisual v2"><span>BRAND<br/>FILM</span></div><div><small>02 · BRAND / PRODUCTION</small><h3>Make the story impossible to scroll past.</h3></div></article><article className="workCard"><div className="fakeVisual v3"><span>AI<br/>AUTOMATION</span></div><div><small>03 · AI / SYSTEMS</small><h3>Put repetitive growth work on autopilot.</h3></div></article></div></section>
<section id="industries" className="industry2"><div className="eyebrow2">BUILT FOR AMBITION</div><h2>Different industries.<br/><em>Same obsession.</em></h2><div className="industryList">{industries.map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><i>↗</i></div>)}</div></section>
<section id="events" className="events2"><div className="eventCopy"><div className="eyebrow2">EXPERIENCES / CULTURE</div><h2>Big moments<br/><em>deserve bigger stories.</em></h2><p>We build the digital layer around marriages, red carpets, corporate events, launches and experiences—from campaign strategy and guest journeys to content, creators and post-event storytelling.</p><a className="limeBtn" href="#contact">Create an experience ↗</a></div><div className="eventStack">{events.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong><i>↗</i></div>)}</div></section>
<section className="ai2"><div className="eyebrow2">THE DIGITALE ENGINE</div><h2>AI isn't another service.<br/><span>It's how we work.</span></h2><p>Research → strategy → creative → execution → measurement → learning. Our internal AI layer connects the whole operation so ideas move faster and every campaign gets smarter.</p><div className="aiLine"><span>RESEARCH</span><b>→</b><span>CREATE</span><b>→</b><span>LAUNCH</span><b>→</b><span>LEARN</span></div></section>
<section className="founders2"><div className="eyebrow2">FOUNDERS</div><h2>Built by people who<br/><em>build things.</em></h2><div className="founderGrid"><div><div className="portrait">USK</div><h3>Uma Saravana Kumar</h3><p>Product · AI · Strategy</p></div><div><div className="portrait">SV</div><h3>Siva Veerapaneni</h3><p>Business · Growth · Creative</p></div></div></section>
<section id="contact" className="contact2"><div className="eyebrow2">START A CONVERSATION</div><h2>Have something<br/><em>worth building?</em></h2><p>Tell us what you're trying to achieve. We'll figure out the digital system around it.</p><a className="limeBtn" href="mailto:hello@digitalemedia.in">hello@digitalemedia.in ↗</a></section>
<footer className="footer2"><span>DIGITALE MEDIA®</span><span>AI · CREATIVE · GROWTH</span><span>HYDERABAD / INDIA · 2026</span></footer></main>