import type { PrototypeProperty } from "./types";

export const properties: PrototypeProperty[] = [
  {
    id: "meadowline-house",
    name: "Meadowline House",
    location: "Kondapur",
    price: 14200000,
    bedrooms: 3,
    area: 1680,
    propertyType: "apartment",
    amenities: ["pool", "gym", "security", "parking", "community"],
    purposeFit: ["living", "investment"],
    commuteTags: ["workplace", "schools", "hitec city"],
    description: "A three-bedroom apartment concept with shared green space and everyday amenities.",
    matchFactors: ["A balanced configuration for shared family spaces.", "Several daily-use amenities are included in the prototype brief."],
    thingsToConsider: ["The stated price and availability are fictional.", "Commute times have not been modelled."],
  },
  {
    id: "kite-courtyard",
    name: "Kite Courtyard",
    location: "Nallagandla",
    price: 11800000,
    bedrooms: 3,
    area: 1520,
    propertyType: "apartment",
    amenities: ["community", "security", "parking", "green space", "schools"],
    purposeFit: ["living"],
    commuteTags: ["workplace", "schools", "financial district"],
    description: "A family-oriented apartment concept organized around a quiet shared courtyard.",
    matchFactors: ["Shared outdoor space supports a community-oriented brief.", "Its three-bedroom layout leaves room for changing family needs."],
    thingsToConsider: ["The stated price and availability are fictional.", "Nearby services are illustrative, not verified."],
  },
  {
    id: "orchard-fold",
    name: "Orchard Fold",
    location: "Tellapur",
    price: 17600000,
    bedrooms: 4,
    area: 2280,
    propertyType: "villa",
    amenities: ["garden", "parking", "security", "community"],
    purposeFit: ["living"],
    commuteTags: ["workplace", "schools", "financial district"],
    description: "A four-bedroom villa concept with private outdoor space and a small shared community.",
    matchFactors: ["A villa layout offers more separation between shared and private areas.", "Private garden space is part of the concept."],
    thingsToConsider: ["The stated price and availability are fictional.", "A villa may involve more upkeep than an apartment."],
  },
  {
    id: "mica-grove",
    name: "Mica Grove",
    location: "Gachibowli",
    price: 16500000,
    bedrooms: 3,
    area: 1740,
    propertyType: "apartment",
    amenities: ["gym", "pool", "security", "parking", "metro"],
    purposeFit: ["living", "investment"],
    commuteTags: ["workplace", "financial district", "metro", "hitec city"],
    description: "A connected three-bedroom apartment concept close to workday destinations.",
    matchFactors: ["The location is tagged for workplace and Financial District proximity.", "A three-bedroom plan combines shared and private space."],
    thingsToConsider: ["The stated price and availability are fictional.", "Proximity tags do not represent measured travel times."],
  },
  {
    id: "beryl-house",
    name: "Beryl House",
    location: "Miyapur",
    price: 9200000,
    bedrooms: 2,
    area: 1260,
    propertyType: "apartment",
    amenities: ["security", "parking", "metro", "community"],
    purposeFit: ["living", "investment"],
    commuteTags: ["workplace", "metro", "schools"],
    description: "A compact two-bedroom apartment concept with a focus on practical essentials.",
    matchFactors: ["A lower illustrative price point than the larger homes in this set.", "Metro and community amenities are part of the concept."],
    thingsToConsider: ["The stated price and availability are fictional.", "The two-bedroom plan may not suit a need for additional rooms."],
  },
  {
    id: "amber-courtyard",
    name: "Amber Courtyard",
    location: "Kokapet",
    price: 18500000,
    bedrooms: 3,
    area: 1810,
    propertyType: "apartment",
    amenities: ["pool", "gym", "security", "parking", "community"],
    purposeFit: ["living", "investment"],
    commuteTags: ["workplace", "financial district", "schools"],
    description: "A three-bedroom apartment concept with shared recreation and access to work districts.",
    matchFactors: ["The location is tagged near the Financial District.", "Shared amenities support both daily use and tenant appeal."],
    thingsToConsider: ["The stated price and availability are fictional.", "Investment performance is not forecast."],
  },
  {
    id: "slate-terrace",
    name: "Slate Terrace",
    location: "Jubilee Hills",
    price: 26800000,
    bedrooms: 4,
    area: 2460,
    propertyType: "villa",
    amenities: ["garden", "parking", "security", "schools"],
    purposeFit: ["living"],
    commuteTags: ["workplace", "schools", "metro"],
    description: "A larger independent-home concept with private garden space in an established neighbourhood.",
    matchFactors: ["The four-bedroom plan offers additional room for household needs.", "Private outdoor space is included in the concept."],
    thingsToConsider: ["The stated price and availability are fictional.", "The higher price point may exceed a moderated budget."],
  },
  {
    id: "blue-hour-residences",
    name: "Blue Hour Residences",
    location: "Manikonda",
    price: 10800000,
    bedrooms: 2,
    area: 1320,
    propertyType: "apartment",
    amenities: ["gym", "security", "parking", "community"],
    purposeFit: ["living", "investment"],
    commuteTags: ["workplace", "financial district", "hitec city"],
    description: "A two-bedroom apartment concept between residential routines and workday destinations.",
    matchFactors: ["The location is tagged for access to work districts.", "A compact configuration keeps the illustrative entry price lower."],
    thingsToConsider: ["The stated price and availability are fictional.", "Commute times have not been modelled."],
  },
  {
    id: "cedar-steps",
    name: "Cedar Steps",
    location: "Narsingi",
    price: 15500000,
    bedrooms: 3,
    area: 1690,
    propertyType: "apartment",
    amenities: ["green space", "pool", "security", "parking", "schools"],
    purposeFit: ["living"],
    commuteTags: ["workplace", "schools", "financial district"],
    description: "A three-bedroom apartment concept balancing shared green space and practical family amenities.",
    matchFactors: ["Green space and schools are part of the stated concept.", "The three-bedroom layout matches a growing-household brief."],
    thingsToConsider: ["The stated price and availability are fictional.", "Nearby services are illustrative, not verified."],
  },
  {
    id: "paperbark-place",
    name: "Paperbark Place",
    location: "Kukatpally",
    price: 13400000,
    bedrooms: 3,
    area: 1580,
    propertyType: "apartment",
    amenities: ["metro", "gym", "security", "parking"],
    purposeFit: ["living", "investment"],
    commuteTags: ["workplace", "metro", "hitec city"],
    description: "A transit-minded three-bedroom apartment concept with a straightforward amenity set.",
    matchFactors: ["Metro is included among the proximity tags.", "Its configuration works for shared living or a future tenant brief."],
    thingsToConsider: ["The stated price and availability are fictional.", "Transit proximity has not been independently verified."],
  },
  {
    id: "little-arc-house",
    name: "Little Arc House",
    location: "Begumpet",
    price: 7900000,
    bedrooms: 1,
    area: 890,
    propertyType: "apartment",
    amenities: ["metro", "security", "parking"],
    purposeFit: ["investment"],
    commuteTags: ["workplace", "metro", "airport"],
    description: "A one-bedroom apartment concept designed around a compact city base.",
    matchFactors: ["The compact configuration sits at the lowest illustrative price point.", "Metro and airport are included in the proximity tags."],
    thingsToConsider: ["The stated price and availability are fictional.", "A one-bedroom layout is not suited to every household."],
  },
  {
    id: "red-earth-courtyard",
    name: "Red Earth Courtyard",
    location: "Shamshabad",
    price: 22400000,
    bedrooms: 4,
    area: 2520,
    propertyType: "villa",
    amenities: ["garden", "parking", "security", "community"],
    purposeFit: ["living"],
    commuteTags: ["airport", "workplace"],
    description: "A four-bedroom villa concept with a private garden and a quieter edge-of-city setting.",
    matchFactors: ["Private outdoor space and a larger layout are central to the concept.", "The airport appears in its proximity tags."],
    thingsToConsider: ["The stated price and availability are fictional.", "A quieter setting may mean longer journeys to some city destinations."],
  },
];
